# Generated by Django 6.0.7 on 2026-07-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boilerplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('template', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boilerplates', to='problems.problem')),
            ],
            options={
                'unique_together': {('problem', 'language')},
            },
        ),
    ]
